---
# Source: prometheus-rabbitmq-exporter/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-rabbitmq-exporter
  labels:
    app: prometheus-rabbitmq-exporter
    chart: prometheus-rabbitmq-exporter-1.2.0
    release: prometheus-rabbitmq-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-rabbitmq-exporter
      release: prometheus-rabbitmq-exporter
  template:
    metadata:
      labels:
        app: prometheus-rabbitmq-exporter
        release: prometheus-rabbitmq-exporter
      annotations:
        {}
    spec:
      serviceAccountName: default
      containers:
        - name: prometheus-rabbitmq-exporter
          image: "kbudde/rabbitmq-exporter:v0.29.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBIT_URL
              value: "http://rabbitmq:15672"
            - name: RABBIT_USER
              value: "guest"
            - name: RABBIT_PASSWORD
              value: "guest"
            - name: PUBLISH_PORT
              value: "9419"
            - name: LOG_LEVEL
              value: "info"
            - name: RABBIT_CAPABILITIES
              value: "bert,no_sort"
            - name: INCLUDE_QUEUES
              value: ".*"
            - name: INCLUDE_VHOST
              value: ".*"
            - name: SKIP_QUEUES
              value: "^$"
            - name: SKIPVERIFY
              value: "false"
            - name: SKIP_VHOST
              value: "^$"
            - name: RABBIT_EXPORTERS
              value: "exchange,node,overview,queue"
            - name: OUTPUT_FORMAT
              value: "TTY"
            - name: RABBIT_TIMEOUT
              value: "30"
            - name: MAX_QUEUES
              value: "0"
          ports:
            - containerPort: 9419
              name: publish
          livenessProbe:
            httpGet:
              path: /
              port: publish
          readinessProbe:
            httpGet:
              path: /
              port: publish
          resources:
            {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["all"]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10002
